name: Build and Release
on:
  push:
    tags:
     - 'v*'
jobs:
  build-and-deploy:
    runs-on: ubnutu-latest
    steps:
      - name: Обновление Кода (Zip)
        uses: actions/checkout@v3

      - name: Created Artifact (Zip)
        run: |
          zip -r project-v1.zip main.py project.py test_logic.py

      - name: Create Release 
        uses: Softprops/action-gh-release@v1

        with:
          files: project-v.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


